from research.web import get_web_content
from research.academic import get_academic_content
from research.video import get_video_content

def generate_report(topic, profile):
    web = get_web_content(topic)
    academic = get_academic_content(topic)
    video = get_video_content(topic)

    report = f"""
# {topic} Learning Report

## 👤 Learner Profile
- Prior Knowledge: {profile['knowledge']}
- Interest: {profile['interest']}
- Preferred Format: {profile['format']}

---

## 🌐 Web Content
{web}

## 📚 Academic Sources
{academic}

## 🎥 Video Transcripts
{video}

---

## 📌 Recommended Next Steps
- Read more on {profile['interest']}
- Watch YouTube videos or MOOCs on {topic}
- Explore visualizations or real-world examples

---

*Report generated by Enhanced Learning Assistant.*
"""
    return report
